export class TaskModel {
  public _id!: string; // generated by mongoDB
  public category!: string;
  public title!: string;
  public context!: string;
  public taskDate!: string;
  public taskTime!: string;
  public completed!: boolean;
  public createdAt!: Date; // generated by mongoDB
  public updatedAt!: Date; // generated by mongoDB
  constructor(model?: any) {
    Object.assign(this, model);
  }

}
